### ISSUE TITLE
Manifest inconsistency

### ISSUE THREAD

**Issue by jaruba** [axtgr/stremio-imvdb#1]
Hi, you are using a type for your catalog:
https://github.com/axtgr/stremio-imvdb/blob/master/stremio_imvdb/addon.py#L31

That is not stated in manifest.types:
https://github.com/axtgr/stremio-imvdb/blob/master/stremio_imvdb/addon.py#L26

I believe this might be the reason the "Music Videos" catalog type only shows on the Desktop app, but not in the Android app.

**Comment by axtgr** [comment]
Thanks for pointing this out! I can't test it currently, will come to it in a week.

@jaruba are such custom types even supported? AFAIK this behavior is undocumented, so I'm not sure if I'm just using a hack or not.

**Comment by jaruba** [comment]
they are now, they were in the process of being implemented across Stremio apps through the contest period

they will also be documented soon
